version: 2.1
executors:
  openjdk_latest-node:
    docker:
      - image: circleci/openjdk:latest-node
jobs:
  build_sfdx_node: 
    working_directory: ~/ci_app
    executor: openjdk_latest-node
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: |
            echo ${DOCKER_PASS} | docker login -u ${DOCKER_USERNAME} --password-stdin
            docker build -t bluetel/node-sfdx:latest -t bluetel/node-sfdx:${CIRCLE_BUILD_NUM} sfdx/node-alpine
            docker push bluetel/node-sfdx:latest
            docker push bluetel/node-sfdx:${CIRCLE_BUILD_NUM}
workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 2 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build_sfdx_node
