version: 2.1
jobs:
  build_image: 
    working_directory: ~/ci_app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: |
            echo ${DOCKER_PASS} | docker login -u ${DOCKER_USERNAME} --password-stdin
            docker build -t bluetel/node-sfdx:latest
            docker push bluetel/node-sfdx:latest
workflows:
  version: 2
  validate:
    jobs:
      - build_image:
          filters:
            branches:
              only:
                - master